// <auto-generated />
namespace MusicHelp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TablatureEdits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TablatureEdits));
        
        string IMigrationMetadata.Id
        {
            get { return "202111300354122_Tablature Edits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
