// <auto-generated />
namespace MusicHelp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MoreWorkWithStarredMethods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoreWorkWithStarredMethods));
        
        string IMigrationMetadata.Id
        {
            get { return "202111292155399_More Work With Starred Methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
