// <auto-generated />
namespace MusicHelp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class StarredMethodAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StarredMethodAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202111292025083_Starred Method Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
